#! /bin/sh

# autostart

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop= '^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#F5EA5A"
bspc config normal_border_color         "#434242"
bspc config active_border_color         "#FF7B54"

#Autostart
#wallpapers
# WP=$HOME/Pictures/Wallpapers/1021524.png
# feh --bg-scale $WP &
 nitrogen --restore &

#Monitor
xrandr --output HDMI-1 --mode 1920x1080 --rate 75 above eDP-1 &

~/.config/polybar/launch.sh &
nm-applet --indicator &

flameshot &

fusuma &

picom &
~/.config/bspwm/scripts/bat_notifier.sh

